# Generated by Django 5.1.6 on 2025-03-01 08:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_alter_spapi_credential_access_token_and_more'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='StoreProfile',
        ),
    ]
