# Generated by Django 5.1.6 on 2025-02-25 07:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='seller', max_length=400, unique=True)),
                ('slug', models.SlugField(blank=True, default='<django.db.models.fields.CharField>', max_length=100, unique=True)),
                ('platform', models.CharField(default='Ecom', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
