# Generated by Django 5.1.6 on 2025-03-01 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_store_storeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDebrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unshipped_orders', models.IntegerField(blank=True, default=None, null=True)),
                ('last_updation', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.storeprofile')),
            ],
        ),
    ]
