# Generated by Django 5.1.6 on 2025-03-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyapicredentials',
            name='store_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
