# Generated by Django 5.1.6 on 2025-03-14 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPAPI_Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('access_token_updation_time', models.DateTimeField(default=None)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.storeprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
