# Generated by Django 5.1.6 on 2025-02-24 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
        ('dashboard', '0002_store_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spapi_credential',
            name='store',
            field=models.ForeignKey(default='store', on_delete=django.db.models.deletion.CASCADE, to='dashboard.store'),
        ),
        migrations.AlterField(
            model_name='spapi_credential',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
