# Generated by Django 5.1.6 on 2025-02-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_spapi_credential_store'),
        ('dashboard', '0002_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spapi_credential',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.store'),
        ),
    ]
