# Generated by Django 5.1.6 on 2025-03-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_spapi_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='spapi_limits',
            name='endpoint',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
