# Generated by Django 5.1.3 on 2025-01-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPAPI_Credential',
        ),
    ]
